# Generated by Django 5.0.6 on 2024-05-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ans',
        ),
    ]
