# Generated by Django 5.0.6 on 2024-05-29 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
